### PR TITLE
New DartPad Sample App Added to Readme + .gif added to /art

### PR DESCRIPTION
**Pull request by theindianappguy**
As instructed by redbrogdon@google.com I have prepared a sample application for GSOC 2020

Screenshot 2020-03-07 at 2 27 47 PM

### CODE REVIEW

**Comment by divyanshub024** [comment]
Can you resolve the conflicts?

**Comment by divyanshub024** [comment]
There are some lint warning.
```
This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Tile.imagePathUrl, Tile.tileIndex, Tile.parent - line 265
```

**Comment by theindianappguy** [comment]
Yes i will

**Comment by theindianappguy** [comment]
What should i do now?

**Comment by divyanshub024** [comment]
I'm getting this warning on dartPad. Please fix it.
```
This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Tile.imagePathUrl, Tile.tileIndex, Tile.parent - line 282
```

**Comment by theindianappguy** [comment]
i would request to give it a look again i have already updated it before https://dartpad.dev/482dbd401031ab9f74b0fa3de705ad2f

**Comment by divyanshub024** [comment]
@theindianappguy I'm still getting this.
Screenshot 2020-03-12 at 9 55 35 AM

**Comment by theindianappguy** [comment]
Please try to open in incognito

**Comment by theindianappguy** [comment]
The problem is simple using final i have updated it already

Screenshot 2020-03-12 at 6 01 25 PM

**Pull request merged**
