### PR TITLE
Slivers App

### PR DESCRIPTION
**Pull request by GAyan17**
Added a simple implementation of Slivers List Sample App. Will update README further again.

### CODE REVIEW

**Review by GOVINDDIXIT — COMMENTED** [review]
Hi @GAyan17 You can also add the GIF for the same in the readme. Thanks

**Comment by GAyan17** [comment]
SliversListApp

**Comment by divyanshub024** [comment]
Hey @GAyan17 !! Thanks a lot for this PR but this sample cannot be added to the list as it's quite basic. Feel free to work on it and come up with something new and awesome.

**Comment by GAyan17** [comment]
Okay sure @divyanshub024

**Pull request closed without merging**
