### PR TITLE
New Sample: Fluttery Bubbles Animation game

### PR DESCRIPTION
**Pull request by jddeep**
New Sample: Fluttery Bubbles Animation game

fluttery_bubbles

### CODE REVIEW

**Comment by jddeep** [comment]
@divyanshub024 Please have a look :) Although this animation game sample is inspired from the animations sample from dartpad, this really helped me understand more about `AnimatedContainers` and animations in general. Thought this could help others as well if we keep this as a sample here. Do let me know your thoughts. Thanks

**Comment by divyanshub024** [comment]
@jddeep What is the difference between this sample and the animation sample from dartpad.

**Comment by jddeep** [comment]
@divyanshub024 The animation sample is just a showcase of the animation but here, I have added a little bit more meaning and making a bit interesting.

**Comment by divyanshub024** [comment]
How did you added more meaning and more interesting? I would like to know what changes are there. I can only merge this if there are some notable changes otherwise it can be considered as plagiarised.

**Comment by jddeep** [comment]
@divyanshub024 Agreed. The changes to be precise include things like brightness toggle, plain discs -> flutter bubbles and some other minor changes like a meaningful appbar. Do let me know if we cannot merge this here, will close this down. Only made the PR to have an animation sample here as the dartpad sample was quite helpful. But anyways, do let me know. Thanks

**Comment by jddeep** [comment]
You know what, Let me close this. I am making something cooler and hopefully, it will add more value to new devs and help them understand animations better. Thanks.

**Pull request closed without merging**
